
services:
  shopping:
    build:
      context: .
      dockerfile: Dockerfile
    image: abatan/shopping:7
    restart: always
    container_name: shopping
    depends_on:
      - mysql
    ports:
      - "900:80"

  mysql:
    image: mysql:5.7
    restart: always
    container_name:  mysql-shopping
    # ports:
    #   - "3305:3306"
    environment:
      MYSQL_DATABASE: deft
      MYSQL_ROOT_USER: root 
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "9195:80"
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1